version: '3'
services:
  jenkins:
    image: 'registry.aliyuncs.com/zhangguanzhang/jenkins:lts-docker'
    container_name: jenkins
    restart: unless-stopped 
    ports: 
      - '8080:8080'
      - '50000:50000'
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - './data:/var/jenkins_home'
      - /var/run/docker.sock:/var/run/docker.sock
      - '/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime'
    networks:
      - jenkins
networks:
  jenkins:
    external: false
